const questions = [

    { q: "👤 <span class='plus-sign'>+</span> 🐝", a: "BAŞARI" },
    { q: "🍯 <span class='plus-sign'>+</span> 🔟", a: "BALON" },
    { q: "🐘 <span class='plus-sign'>+</span> 👣", a: "FİLİZ" },
    { q: "🌙 <span class='plus-sign'>+</span> ⚪", a: "AYAK" },
    { q: "❄️ <span class='plus-sign'>+</span> 🐟", a: "KARTON" },
    { q: "🧊 <span class='plus-sign'>+</span> E", a: "KÜPE" },
    { q: "🏰 <span class='plus-sign'>+</span> M", a: "KALEM" },
    { q: "🌊 <span class='plus-sign'>+</span> 6️⃣", a: "DENİZALTI" },
    { q: "🔋 <span class='plus-sign'>+</span> 🔫", a: "PİLAV" },
    { q: "💪 <span class='plus-sign'>+</span> 🍽️", a: "KOLYE" },
    { q: "♟️ <span class='plus-sign'>+</span> 📞", a: "MATARA" },
    { q: "⬛ <span class='plus-sign'>+</span> ✏️", a: "KARAKALEM" },
    { q: "🦆 <span class='plus-sign'>+</span> ⬜", a: "KAZAK" },
    { q: "🌿 <span class='plus-sign'>+</span> ✋", a: "OTEL" },
    { q: "1️⃣ <span class='plus-sign'>+</span> ✋", a: "TEKEL" },
    { q: "1️⃣ <span class='plus-sign'>+</span> 🪖", a: "TEKER" },
    { q: "💥 <span class='plus-sign'>+</span> 🐎 <span class='plus-sign'>+</span> ༄", a: "PATATES" },
    { q: "🍯 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🔟", a: "BALKON" },
    { q: "B <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> E", a: "BERE" },
    { q: "🐎 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> 🥩", a: "ATLET" },
    { q: "🎵 <span class='plus-sign'>+</span> ♟️ <span class='plus-sign'>+</span> 🎼", a: "DOMATES" },
    { q: "⬅️ <span class='plus-sign'>+</span> U <span class='plus-sign'>+</span> ❤️", a: "SOLUCAN" },
    { q: "M <span class='plus-sign'>+</span> ⏰ <span class='plus-sign'>+</span> 🌿", a: "MANDAL" },
    { q: "👁️ <span class='plus-sign'>+</span> 🌋 <span class='plus-sign'>+</span> A", a: "BAKLAVA" },
    { q: "Ⓜ️ <span class='plus-sign'>+</span> 🌿 <span class='plus-sign'>+</span> ✋", a: "MOTEL" },
    { q: "B <span class='plus-sign'>+</span> ✋ <span class='plus-sign'>+</span> A", a: "BELA" },
    { q: "🍯 <span class='plus-sign'>+</span> 🛬 <span class='plus-sign'>+</span> A", a: "BALİNA" },
    { q: "Ⓜ️ <span class='plus-sign'>+</span> ⏰ <span class='plus-sign'>+</span> 🪾", a: "MANDAL" },
    { q: "S <span class='plus-sign'>+</span> ⏰ <span class='plus-sign'>+</span> 🌿 <span class='plus-sign'>+</span> 🍽️", a: "SANDALYE" },
    { q: "❄️ <span class='plus-sign'>+</span> N <span class='plus-sign'>+</span> A <span class='plus-sign'>+</span> 🌸", a: "KARNABAHAR" },
    { q: "💥 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> I <span class='plus-sign'>+</span> ❤️", a: "PATLICAN" },
    { q: "💥 <span class='plus-sign'>+</span> 🐎 <span class='plus-sign'>+</span> E <span class='plus-sign'>+</span> S", a: "PATATES" },
    { q: "✋ <span class='plus-sign'>+</span> D <span class='plus-sign'>+</span> İ <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> ↔️", a: "ELDİVEN" },
    { q: "T <span class='plus-sign'>+</span> ✋ <span class='plus-sign'>+</span> E <span class='plus-sign'>+</span> F <span class='plus-sign'>+</span> 🔟", a: "TELEFON" },
    { q: "Ⓜ️ <span class='plus-sign'>+</span> ⏰ <span class='plus-sign'>+</span> 🪾 <span class='plus-sign'>+</span> 🛬 <span class='plus-sign'>+</span> A", a: "MANDALİNA" },
    { q: "T <span class='plus-sign'>+</span> ✋ <span class='plus-sign'>+</span> 🏠 <span class='plus-sign'>+</span> 👁️ <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔟", a: "TELEVİZYON" },
    { q: "❄️ <span class='plus-sign'>+</span> A <span class='plus-sign'>+</span> N <span class='plus-sign'>+</span> 🐘", a: "KARANFİL" },
    { q: "☁️ <span class='plus-sign'>+</span> 🐦 <span class='plus-sign'>+</span> 🕸️ <span class='plus-sign'>+</span> I", a: "GÖKKUŞAĞI" },
    { q: "🔔 <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> 🏰", a: "ÇANAKKALE" },
    { q: "🍯 <span class='plus-sign'>+</span> 💂 <span class='plus-sign'>+</span> ⬇️", a: "BALERİN" },
    { q: "💳 <span class='plus-sign'>+</span> 🔟", a: "KARTON" },
    { q: "🍯 <span class='plus-sign'>+</span> 🔟", a: "BALON" },
    { q: "🏁 <span class='plus-sign'>+</span> 🔎", a: "MATARA" },
    { q: "🧣 <span class='plus-sign'>+</span> ✅", a: "ŞALVAR" },
    { q: "🌾 <span class='plus-sign'>+</span> ⌛", a: "SAZAN" },
    { q: "💪 <span class='plus-sign'>+</span> 🔟", a: "KOLON" },
    { q: "🦢 <span class='plus-sign'>+</span> ⌛", a: "KAZAN" },
    { q: "🐦 <span class='plus-sign'>+</span> ⚪", a: "KUŞAK" },
    { q: "👤 <span class='plus-sign'>+</span> ⚪", a: "BAŞAK" },
    { q: "⚪ <span class='plus-sign'>+</span> 🌊", a: "AKDENİZ" },
    { q: "⚫ <span class='plus-sign'>+</span> 💪", a: "KARAKOL" },
    { q: "💪 <span class='plus-sign'>+</span> 🍞", a: "KOLYE" },
    { q: "🌙 <span class='plus-sign'>+</span> ⚪", a: "AYAK" },
    { q: "👤 <span class='plus-sign'>+</span> 🐝", a: "BAŞARI" },
    { q: "🔴 <span class='plus-sign'>+</span> ⌛", a: "ALAN" },
    { q: "🌙 <span class='plus-sign'>+</span> 📉", a: "AYAZ" },
    { q: "📷 <span class='plus-sign'>+</span> 🥤", a: "ÇEKİÇ" },
    { q: "🪵 <span class='plus-sign'>+</span> ⚪", a: "DALAK" },
    { q: "🏠 <span class='plus-sign'>+</span> 🦌", a: "EVREN" },
    { q: "☀️ <span class='plus-sign'>+</span> 🟰", a: "GÜNEŞ" },
    { q: "📞 <span class='plus-sign'>+</span> 🌙", a: "HATAY" },
    { q: "🩸 <span class='plus-sign'>+</span> 🔴", a: "KANAL" },
    { q: "🦢 <span class='plus-sign'>+</span> ⚪", a: "KAZAK" },
    { q: "💪 <span class='plus-sign'>+</span> 🌙", a: "KOLAY" },
    { q: "🟣 <span class='plus-sign'>+</span> 🔴", a: "MORAL" },
    { q: "📞 <span class='plus-sign'>+</span> 👨‍👩‍👧‍👦", a: "TELSİZ" },
    { q: "⚽ <span class='plus-sign'>+</span> 🔴", a: "TOPAL" },
    { q: "✅ <span class='plus-sign'>+</span> 🏙️", a: "VARİL" },
    { q: "⚪ <span class='plus-sign'>+</span> 🧔", a: "AKBABA" },
    { q: "🍯 <span class='plus-sign'>+</span> 🥩", a: "BALET" },
    { q: "❤️ <span class='plus-sign'>+</span> 🪖", a: "CANER" },
    { q: "🧎 <span class='plus-sign'>+</span> ✋", a: "DİZEL" },
    { q: "🩲 <span class='plus-sign'>+</span> 🐴", a: "DONAT" },
    { q: "🪖 <span class='plus-sign'>+</span> 🏨", a: "ERHAN" },
    { q: "🛑 <span class='plus-sign'>+</span> 🩸", a: "KALKAN" },
    { q: "✂️ <span class='plus-sign'>+</span> 🪖", a: "KESER" },
    { q: "💵 <span class='plus-sign'>+</span> 🔴", a: "KURAL" },
    { q: "🧲 <span class='plus-sign'>+</span> ⌛", a: "NALAN" },
    { q: "🔟 <span class='plus-sign'>+</span> 🌙", a: "ONAY" },
    { q: "🔋 <span class='plus-sign'>+</span> 🥤", a: "PİLİÇ" },
    { q: "🔚 <span class='plus-sign'>+</span> ✈️", a: "SONUÇ" },
    { q: "💧 <span class='plus-sign'>+</span> 🐴", a: "SUAT" },
    { q: "👑 <span class='plus-sign'>+</span> 💨 <span class='plus-sign'>+</span> 🪖", a: "ŞAHESER" },
    { q: "✊ <span class='plus-sign'>+</span> 🛑", a: "TUTKAL" },
    { q: "✈️ <span class='plus-sign'>+</span> ⚪", a: "UÇAK" },
    { q: "🛥️ <span class='plus-sign'>+</span> ⚪", a: "YATAK" },
    { q: "🏹 <span class='plus-sign'>+</span> 🕳️", a: "YAYIN" },
    { q: "💯 <span class='plus-sign'>+</span> 🐑", a: "YÜZME" },
    { q: "🎲 <span class='plus-sign'>+</span> 🪖", a: "ZARAR" },
    { q: "🩸 <span class='plus-sign'>+</span> 🐴", a: "KANAT" },
    { q: "🐘 <span class='plus-sign'>+</span> 👣", a: "FİLİZ" },
    { q: "🔋 <span class='plus-sign'>+</span> 🌿", a: "PİLOT" },
    { q: "🍯 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🔟", a: "BALKON" },
    { q: "Ç <span class='plus-sign'>+</span> 🐴 <span class='plus-sign'>+</span> 🔴", a: "ÇATAL" },
    { q: "S <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🔴", a: "SANAL" },
    { q: "K <span class='plus-sign'>+</span> 🔓 <span class='plus-sign'>+</span> ⚪", a: "KAÇAK" },
    { q: "K <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> ⚪", a: "KAYAK" },
    { q: "D <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> ⚪", a: "DAYAK" },
    { q: "☕ <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "ÇAYLAK" },
    { q: "K <span class='plus-sign'>+</span> 🔟 <span class='plus-sign'>+</span> ⚪", a: "KONAK" },
    { q: "🛑 <span class='plus-sign'>+</span> ⚪", a: "DURAK" },
    { q: "K <span class='plus-sign'>+</span> 💵 <span class='plus-sign'>+</span> ⚪", a: "KURAK" },
    { q: "Y <span class='plus-sign'>+</span> 🥩 <span class='plus-sign'>+</span> 🪖", a: "YETER" },
    { q: "M <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> ⚪", a: "MERAK" },
    { q: "Y <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> ⚪", a: "YANAK" },
    { q: "🌿 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "OTLAK" },
    { q: "💧 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "SULAK" },
    { q: "B <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> 🥩", a: "BALET" },
    { q: "⌛ <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🥩", a: "ANKET" },
    { q: " 1️⃣ <span class='plus-sign'>+</span> 📉", a: "BİRAZ" },
    { q: "🩸 <span class='plus-sign'>+</span> 🔴", a: "KANAL" },
    { q: "T <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> ⌛", a: "TALAN" },
    { q: "🛶 <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🐴", a: "SALTANAT" },
    { q: "G <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> 🐴 <span class='plus-sign'>+</span> A", a: "GALATA" },
    { q: "M <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> G <span class='plus-sign'>+</span> 🔴", a: "MANGAL" },
    { q: "S <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🪵", a: "SANDAL" },
    { q: "M <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🪵", a: "MANDAL" },
    { q: "❄️ <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> 🔴", a: "KARTAL" },
    { q: "S <span class='plus-sign'>+</span> 🕳️ <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔴", a: "SİNYAL" },
    { q: " <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔟", a: "KANYON" },
    { q: "P <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> 🔟", a: "PANTALON" },
    { q: "G <span class='plus-sign'>+</span> 📉 <span class='plus-sign'>+</span> 🥩 <span class='plus-sign'>+</span> E", a: "GAZETE" },
    { q: "❄️ <span class='plus-sign'>+</span> ⚽ <span class='plus-sign'>+</span> U", a: "KARTOPU" },
    { q: "T <span class='plus-sign'>+</span> ⚽ <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> ⚪", a: "TOPRAK" },
    { q: "H <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> ⌛", a: "HAYRAN" },
    { q: "H <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> ⌛", a: "HAYVAN" },
    { q: "T <span class='plus-sign'>+</span> 🏹 <span class='plus-sign'>+</span> 🐴", a: "TOKAT" },
    { q: "H <span class='plus-sign'>+</span> 🗳️ <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> 🐴", a: "HOYRAT" },
    { q: "R <span class='plus-sign'>+</span> 👻 <span class='plus-sign'>+</span> S <span class='plus-sign'>+</span> 🐴", a: "RUHSAT" },
    { q: "K <span class='plus-sign'>+</span> 📉 <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> Ç", a: "KAZANÇ" },
    { q: "Ş <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> B <span class='plus-sign'>+</span> 🥩", a: "ŞERBET" },
    { q: "H <span class='plus-sign'>+</span> 👣 <span class='plus-sign'>+</span> M <span class='plus-sign'>+</span> 🥩", a: "HİZMET" },
    { q: "🏠 <span class='plus-sign'>+</span> 🦌 <span class='plus-sign'>+</span> 🌊", a: "EVRENSEL" },
    { q: "🔔 <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> 🏰", a: "ÇANAKKALE" },
    { q: "❄️ <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🐘", a: "KARANFİL" },
    { q: "⚫ <span class='plus-sign'>+</span> 🌊", a: "KARADENİZ" },
    { q: "🌲 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> ⌛", a: "AĞAÇKAKAN" },
    { q: "🫗 <span class='plus-sign'>+</span> 🐦 <span class='plus-sign'>+</span> 🕸️ <span class='plus-sign'>+</span> I", a: "GÖKKUŞAĞI" },
    { q: "🫗 <span class='plus-sign'>+</span> 💯 <span class='plus-sign'>+</span> Ü", a: "GÖKYÜZÜ" },
    { q: "⚫ <span class='plus-sign'>+</span> 🛣️ <span class='plus-sign'>+</span> U", a: "KARAYOLU" },
    { q: "👁️ <span class='plus-sign'>+</span> 💧 <span class='plus-sign'>+</span> I", a: "GÖZYAŞI" },
    { q: "🍯 <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> I", a: "BALAYI" },
    { q: "📅 <span class='plus-sign'>+</span> 👤 <span class='plus-sign'>+</span> I", a: "YILBAŞI" },
    { q: "🥛 <span class='plus-sign'>+</span> 🎵 <span class='plus-sign'>+</span> Ç", a: "SÜTLAÇ" },
    { q: "🌹 <span class='plus-sign'>+</span> 🎵 <span class='plus-sign'>+</span> Ç", a: "GÜLLAÇ" },
    { q: "🌊 <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> I", a: "DENİZALTI" },
    { q: "⚪ <span class='plus-sign'>+</span> S <span class='plus-sign'>+</span> 🔎 <span class='plus-sign'>+</span> Y", a: "AKSARAY" },
    { q: "⬅️ <span class='plus-sign'>+</span> U <span class='plus-sign'>+</span> C <span class='plus-sign'>+</span> ⌛", a: "SOLUCAN" },
    { q: "🏨 <span class='plus-sign'>+</span> I <span class='plus-sign'>+</span> M <span class='plus-sign'>+</span> 🖐️ <span class='plus-sign'>+</span> İ", a: "HANIMELİ" },
    { q: "❄️ <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> 👣 <span class='plus-sign'>+</span> 🐕", a: "KARTVİZİT" },
    { q: "❤️ <span class='plus-sign'>+</span> 💵 <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> 🔎 <span class='plus-sign'>+</span> N", a: "CANKURTARAN" },
    { q: "⌛ <span class='plus-sign'>+</span> A <span class='plus-sign'>+</span> 🎶 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> U", a: "ANADOLU" }
];
