const questions = [
    { q: "<i class='fa-solid fa-face-smile' style='color:#e67e22'></i> <span class='plus-sign'>+</span> 🐝", a: "BAŞARI" },
    { q: "🍯 <span class='plus-sign'>+</span> 🔟", a: "BALON" },
    { q: "🐘 <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i>", a: "FİLİZ" },
    { q: "<i class='fa-solid fa-moon' style='color:#f1c40f'></i> <span class='plus-sign'>+</span> ⚪", a: "AYAK" },
    { q: "❄️ <span class='plus-sign'>+</span> <i class='fa-solid fa-fish' style='color:#bdc3c7'></i>", a: "KARTON" },
    { q: "<i class='fa-solid fa-cube' style='color:#3498db'></i> <span class='plus-sign'>+</span> E", a: "KÜPE" },
    { q: "🏰 <span class='plus-sign'>+</span> M", a: "KALEM" },
    { q: "<i class='fa-solid fa-water' style='color:#00a8ff'></i> <span class='plus-sign'>+</span> 6️⃣", a: "DENİZALTI" },
    { q: "<i class='fa-solid fa-battery-full' style='color:#2ecc71'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-crosshairs' style='color:#e74c3c'></i>", a: "PİLAV" },
    { q: "💪 <span class='plus-sign'>+</span> <i class='fa-solid fa-utensils' style='color:#7f8c8d'></i>", a: "KOLYE" },
    { q: "♟️ <span class='plus-sign'>+</span> <i class='fa-solid fa-phone' style='color:#2d3436'></i>", a: "MATARA" },
    { q: "⬛ <span class='plus-sign'>+</span> ✏️", a: "KARAKALEM" },
    { q: "🦆 <span class='plus-sign'>+</span> ⬜", a: "KAZAK" },
    { q: "<i class='fa-solid fa-seedling' style='color:#27ae60'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-hand' style='color:#f1c40f'></i>", a: "OTEL" },
    { q: "1️⃣ <span class='plus-sign'>+</span> <i class='fa-solid fa-hand' style='color:#f1c40f'></i>", a: "TEKEL" },
    { q: "1️⃣ <span class='plus-sign'>+</span> 🪖", a: "TEKER" },
    { q: "💥 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i> <span class='plus-sign'>+</span> ༄", a: "PATATES" },
    { q: "🍯 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🔟", a: "BALKON" },
    { q: "B <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> E", a: "BERE" },
    { q: "<i class='fa-solid fa-horse' style='color:#d35400'></i> <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> 🥩", a: "ATLET" },
    { q: "🎵 <span class='plus-sign'>+</span> ♟️ <span class='plus-sign'>+</span> 🎼", a: "DOMATES" },
    { q: "<i class='fa-solid fa-arrow-left' style='color:#2980b9'></i> <span class='plus-sign'>+</span> U <span class='plus-sign'>+</span> <i class='fa-solid fa-heart' style='color:#e74c3c'></i>", a: "SOLUCAN" },
    { q: "M <span class='plus-sign'>+</span> <i class='fa-regular fa-clock' style='color:#34495e'></i> <span class='plus-sign'>+</span> 🪵", a: "MANDAL" },
    { q: "<i class='fa-solid fa-eye' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-volcano' style='color:#c0392b'></i> <span class='plus-sign'>+</span> A", a: "BAKLAVA" },
    { q: "Ⓜ️ <span class='plus-sign'>+</span> <i class='fa-solid fa-seedling' style='color:#27ae60'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-hand' style='color:#f1c40f'></i>", a: "MOTEL" },
    { q: "B <span class='plus-sign'>+</span> <i class='fa-solid fa-hand' style='color:#f1c40f'></i> <span class='plus-sign'>+</span> A", a: "BELA" },
    { q: "🍯 <span class='plus-sign'>+</span> <i class='fa-solid fa-plane-arrival' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> A", a: "BALİNA" },
    { q: "Ⓜ️ <span class='plus-sign'>+</span> <i class='fa-regular fa-clock' style='color:#34495e'></i> <span class='plus-sign'>+</span> 🪵", a: "MANDAL" },
    { q: "S <span class='plus-sign'>+</span> <i class='fa-regular fa-clock' style='color:#34495e'></i> <span class='plus-sign'>+</span> 🪵 <span class='plus-sign'>+</span> <i class='fa-solid fa-utensils' style='color:#7f8c8d'></i>", a: "SANDALYE" },
    { q: "❄️ <span class='plus-sign'>+</span> N <span class='plus-sign'>+</span> A <span class='plus-sign'>+</span> 🌸", a: "KARNABAHAR" },
    { q: "💥 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> I <span class='plus-sign'>+</span> ❤️", a: "PATLICAN" },
    { q: "💥 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i> +</span> <i class='fa-solid fa-wind' style='color:#bdc3c7'></i> ", a: "PATATES" },
    { q: "✋ <span class='plus-sign'>+</span> D <span class='plus-sign'>+</span> İ <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> ↔️", a: "ELDİVEN" },
    { q: "T <span class='plus-sign'>+</span> ✋ <span class='plus-sign'>+</span> E <span class='plus-sign'>+</span> F <span class='plus-sign'>+</span> 🔟", a: "TELEFON" },
    { q: "T <span class='plus-sign'>+</span> ✋ <span class='plus-sign'>+</span> <i class='fa-solid fa-house' style='color:#e67e22'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔟", a: "TELEVİZYON" },
    { q: "❄️ <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🐘", a: "KARANFİL" },
    { q: "<i class='fa-solid fa-cloud' style='color:#3498db'></i> <span class='plus-sign'>+</span> 🐦 <span class='plus-sign'>+</span> 🕸️ <span class='plus-sign'>+</span> I", a: "GÖKKUŞAĞI" },
    { q: "🔔 <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> 🏰", a: "ÇANAKKALE" },
    { q: "🍯 <span class='plus-sign'>+</span> 💂 <span class='plus-sign'>+</span> ⬇️", a: "BALERİN" },
    { q: "💳 <span class='plus-sign'>+</span> 🔟", a: "KARTON" },
    { q: "🍯 <span class='plus-sign'>+</span> 🔟", a: "BALON" },
    { q: "🏁 <span class='plus-sign'>+</span> 🔎", a: "MATARA" },
    { q: "🧣 <span class='plus-sign'>+</span> ✅", a: "ŞALVAR" },
    { q: "🌾 <span class='plus-sign'>+</span> ⌛", a: "SAZAN" },
    { q: "💪 <span class='plus-sign'>+</span> 🔟", a: "KOLON" },
    { q: "🦢 <span class='plus-sign'>+</span> ⌛", a: "KAZAN" },
    { q: "🐦 <span class='plus-sign'>+</span> ⚪", a: "KUŞAK" },
    { q: "<i class='fa-solid fa-face-smile' style='color:#e67e22'></i> <span class='plus-sign'>+</span> ⚪", a: "BAŞAK" },
    { q: "⚪ <span class='plus-sign'>+</span> 🌊", a: "AKDENİZ" },
    { q: "⚫ <span class='plus-sign'>+</span> 💪", a: "KARAKOL" },
    { q: "💪 <span class='plus-sign'>+</span> 🍞", a: "KOLYE" },
    { q: "🌙 <span class='plus-sign'>+</span> ⚪", a: "AYAK" },
    { q: "<i class='fa-solid fa-face-smile' style='color:#e67e22'></i> <span class='plus-sign'>+</span> 🐝", a: "BAŞARI" },
    { q: "🔴 <span class='plus-sign'>+</span> ⌛", a: "ALAN" },
    { q: "🌙 <span class='plus-sign'>+</span> 📉", a: "AYAZ" },
    { q: "<i class='fa-solid fa-camera' style='color:#34495e'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-glass-water' style='color:#3498db'></i>", a: "ÇEKİÇ" },
    { q: "🪵 <span class='plus-sign'>+</span> ⚪", a: "DALAK" },
    { q: "<i class='fa-solid fa-house' style='color:#e67e22'></i> <span class='plus-sign'>+</span> 🦌", a: "EVREN" },
    { q: "<i class='fa-solid fa-sun' style='color:#f39c12'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-equals' style='color:#2c3e50'></i>", a: "GÜNEŞ" },
    { q: "📞 <span class='plus-sign'>+</span> 🌙", a: "HATAY" },
    { q: "🩸 <span class='plus-sign'>+</span> 🔴", a: "KANAL" },
    { q: "💪 <span class='plus-sign'>+</span> 🌙", a: "KOLAY" },
    { q: "🟣 <span class='plus-sign'>+</span> 🔴", a: "MORAL" },
    { q: "<i class='fa-solid fa-phone' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> 👨‍👩‍👧‍👦", a: "TELSİZ" },
    { q: "<i class='fa-solid fa-basketball' style='color:#d35400'></i> <span class='plus-sign'>+</span> 🔴", a: "TOPAL" },
    { q: "✅ <span class='plus-sign'>+</span> 🏙️", a: "VARİL" },
    { q: "⚪ <span class='plus-sign'>+</span> 🧔", a: "AKBABA" },
    { q: "🍯 <span class='plus-sign'>+</span> 🥩", a: "BALET" },
    { q: "❤️ <span class='plus-sign'>+</span> 🪖", a: "CANER" },
    { q: "🦵 <span class='plus-sign'>+</span> ✋", a: "DİZEL" },
    { q: "🩲 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "DONAT" },
    { q: "🪖 <span class='plus-sign'>+</span> 🏨", a: "ERHAN" },
    { q: "🛑 <span class='plus-sign'>+</span> 🩸", a: "KALKAN" },
    { q: "✂️ <span class='plus-sign'>+</span> 🪖", a: "KESER" },
    { q: "💵 <span class='plus-sign'>+</span> 🔴", a: "KURAL" },
    { q: "🧲 <span class='plus-sign'>+</span> ⌛", a: "NALAN" },
    { q: "🔟 <span class='plus-sign'>+</span> 🌙", a: "ONAY" },
    { q: "<i class='fa-solid fa-battery-full' style='color:#2ecc71'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-glass-water' style='color:#3498db'></i>", a: "PİLİÇ" },
    { q: "<i class='fa-solid fa-flag-checkered' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-plane-departure' style='color:#34495e'></i>", a: "SONUÇ" },
    { q: "💧 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "SUAT" },
    { q: "👑 <span class='plus-sign'>+</span> <i class='fa-solid fa-wind' style='color:#95a5a6'></i> <span class='plus-sign'>+</span> 🪖", a: "ŞAHESER" },
    { q: "✊ <span class='plus-sign'>+</span> 🛑", a: "TUTKAL" },
    { q: "<i class='fa-solid fa-plane-up' style='color:#34495e'></i> <span class='plus-sign'>+</span> ⚪", a: "UÇAK" },
    { q: "🛥️ <span class='plus-sign'>+</span> ⚪", a: "YATAK" },
    { q: "💯 <span class='plus-sign'>+</span> 🐑", a: "YÜZME" },
    { q: "<i class='fa-solid fa-dice' style='color:#e74c3c'></i> <span class='plus-sign'>+</span> AR", a: "ZARAR" },
    { q: "🩸 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "KANAT" },
    { q: "🐘 <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i>", a: "FİLİZ" },
    { q: "🔋 <span class='plus-sign'>+</span> 🌿", a: "PİLOT" },
    { q: "🍯 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🔟", a: "BALKON" },
    { q: "Ç <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i> <span class='plus-sign'>+</span> 🔴", a: "ÇATAL" },
    { q: "S <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🔴", a: "SANAL" },
    { q: "🔓 <span class='plus-sign'>+</span> ⚪", a: "KAÇAK" },
    { q: "K <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> ⚪", a: "KAYAK" },
    { q: "D <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> ⚪", a: "DAYAK" },
    { q: "☕ <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "ÇAYLAK" },
    { q: "K <span class='plus-sign'>+</span> 🔟 <span class='plus-sign'>+</span> ⚪", a: "KONAK" },
    { q: "🛑 <span class='plus-sign'>+</span> ⚪", a: "DURAK" },
    { q: "K <span class='plus-sign'>+</span> 💵 <span class='plus-sign'>+</span> ⚪", a: "KURAK" },
    { q: "Y <span class='plus-sign'>+</span> 🥩 <span class='plus-sign'>+</span> 🪖", a: "YETER" },
    { q: "M <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> ⚪", a: "MERAK" },
    { q: "Y <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> ⚪", a: "YANAK" },
    { q: "🌿 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "OTLAK" },
    { q: "💧 <span class='plus-sign'>+</span> L <span class='plus-sign'>+</span> ⚪", a: "SULAK" },
    { q: "B <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> 🥩", a: "BALET" },
    { q: "⌛ <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> 🥩", a: "ANKET" },
    { q: " 1️⃣ <span class='plus-sign'>+</span> 📉", a: "BİRAZ" },
    { q: "🩸 <span class='plus-sign'>+</span> 🔴", a: "KANAL" },
    { q: "T <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> ⌛", a: "TALAN" },
    { q: "🛶 <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "SALTANAT" },
    { q: "G <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i> <span class='plus-sign'>+</span> A", a: "GALATA" },
    { q: "M <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> G <span class='plus-sign'>+</span> 🔴", a: "MANGAL" },
    { q: "S <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🪵", a: "SANDAL" },
    { q: "M <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🪵", a: "MANDAL" },
    { q: "❄️ <span class='plus-sign'>+</span> 🔴", a: "KARTAL" },
    { q: "S <span class='plus-sign'>+</span> <i class='fa-solid fa-arrow-down' style='color:#34495e'></i> <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔴", a: "SİNYAL" },
    { q: "🩸 <span class='plus-sign'>+</span> Y <span class='plus-sign'>+</span> 🔟", a: "KANYON" },
    { q: "P <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> 🔟", a: "PANTALON" },
    { q: "G <span class='plus-sign'>+</span> 📉 <span class='plus-sign'>+</span> 🥩 <span class='plus-sign'>+</span> E", a: "GAZETE" },
    { q: "❄️ <span class='plus-sign'>+</span> ⚽ <span class='plus-sign'>+</span> U", a: "KARTOPU" },
    { q: "⚽ <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> ⚪", a: "TOPRAK" }, { q: "H <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> ⌛", a: "HAYRAN" },
    { q: "H <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> ⌛", a: "HAYVAN" },
    { q: "T <span class='plus-sign'>+</span> 🏹 <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "TOKAT" },
    { q: "H <span class='plus-sign'>+</span> 🗳️ <span class='plus-sign'>+</span> R <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "HOYRAT" },
    { q: "👻 <span class='plus-sign'>+</span> S <span class='plus-sign'>+</span> <i class='fa-solid fa-horse' style='color:#d35400'></i>", a: "RUHSAT" },
    { q: "K <span class='plus-sign'>+</span> 📉 <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> Ç", a: "KAZANÇ" },
    { q: "Ş <span class='plus-sign'>+</span> 🪖 <span class='plus-sign'>+</span> B <span class='plus-sign'>+</span> 🥩", a: "ŞERBET" },
    { q: "H <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> M <span class='plus-sign'>+</span> 🥩", a: "HİZMET" },
    { q: "🏠 <span class='plus-sign'>+</span> 🦌 <span class='plus-sign'>+</span> 🌊", a: "EVRENSEL" },
    { q: "🔔 <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> 🏰", a: "ÇANAKKALE" },
    { q: "❄️ <span class='plus-sign'>+</span> ⌛ <span class='plus-sign'>+</span> 🐘", a: "KARANFİL" },
    { q: "⚫ <span class='plus-sign'>+</span> 🌊", a: "KARADENİZ" },
    { q: "🌲 <span class='plus-sign'>+</span> K <span class='plus-sign'>+</span> ⚪ <span class='plus-sign'>+</span> ⌛", a: "AĞAÇKAKAN" },
    { q: "<i class='fa-solid fa-cloud' style='color:#3498db'></i> <span class='plus-sign'>+</span> 🐦 <span class='plus-sign'>+</span> 🕸️ <span class='plus-sign'>+</span> I", a: "GÖKKUŞAĞI" },
    { q: "<i class='fa-solid fa-cloud' style='color:#3498db'></i> <span class='plus-sign'>+</span> 💯 <span class='plus-sign'>+</span> Ü", a: "GÖKYÜZÜ" },
    { q: "⚫ <span class='plus-sign'>+</span> 🛣️ <span class='plus-sign'>+</span> U", a: "KARAYOLU" },
    { q: "👁️ <span class='plus-sign'>+</span> <i class='fa-solid fa-droplet' style='color:#3498db'></i> <span class='plus-sign'>+</span> I", a: "GÖZYAŞI" },
    { q: "🍯 <span class='plus-sign'>+</span> 🌙 <span class='plus-sign'>+</span> I", a: "BALAYI" },
    { q: "<i class='fa-regular fa-calendar-days' style='color:#e74c3c'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-face-smile' style='color:#e67e22'></i> <span class='plus-sign'>+</span> I", a: "YILBAŞI" },
    { q: "🥛 <span class='plus-sign'>+</span> 🎵 <span class='plus-sign'>+</span> Ç", a: "SÜTLAÇ" },
    { q: "🌹 <span class='plus-sign'>+</span> 🎵 <span class='plus-sign'>+</span> Ç", a: "GÜLLAÇ" },
    { q: "🌊 <span class='plus-sign'>+</span> 🔴 <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> I", a: "DENİZALTI" },
    { q: "⚪ <span class='plus-sign'>+</span> S <span class='plus-sign'>+</span> 🔎 <span class='plus-sign'>+</span> Y", a: "AKSARAY" },
    { q: "⬅️ <span class='plus-sign'>+</span> U <span class='plus-sign'>+</span> C <span class='plus-sign'>+</span> ⌛", a: "SOLUCAN" },
    { q: "👩 <span class='plus-sign'>+</span> 🖐️ <span class='plus-sign'>+</span> İ", a: "HANIMELİ" },
    { q: "❄️ <span class='plus-sign'>+</span> T <span class='plus-sign'>+</span> V <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-dog' style='color:#d35400'></i>", a: "KARTVİZİT" },
    { q: "❤️ <span class='plus-sign'>+</span> 💵 <span class='plus-sign'>+</span> <i class='fa-solid fa-print' style='color:#34495e'></i> <span class='plus-sign'>+</span> N", a: "CANKURTARAN" },
    { q: "🤱 <span class='plus-sign'>+</span> <i class='fa-solid fa-cloud-showers-heavy' style='color:#3498db'></i>", a: "ANADOLU" },
    { q: "40 <span class='plus-sign'>+</span> <i class='fa-solid fa-shoe-prints' style='color:#2c3e50'></i>", a: "KIRKAYAK" },
    { q: "<i class='fa-solid fa-person-walking' style='color:#e67e22'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-road' style='color:#34495e'></i> <span class='plus-sign'>+</span> U", a: "YAYA YOLU" },
    { q: "<i class='fa-solid fa-money-bill-1' style='color:#27ae60'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-eye' style='color:#2980b9'></i>", a: "PARAGÖZ" },
    { q: "<i class='fa-solid fa-location-dot' style='color:#c0392b'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-earth-americas' style='color:#3498db'></i>", a: "YERKÜRE" },
    { q: "F <span class='plus-sign'>+</span> <i class='fa-solid fa-wind' style='color:#bdc3c7'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-house' style='color:#e67e22'></i>", a: "FESHANE" },
    { q: "<i class='fa-solid fa-book' style='color:#8e44ad'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-check' style='color:#27ae60'></i>", a: "ROMANTİK" },
    { q: "<i class='fa-regular fa-snowflake' style='color:#00CEC9'></i> <span class='plus-sign'>+</span> DAN <span class='plus-sign'>+</span> <i class='fa-solid fa-user' style='color:#2c3e50'></i>", a: "KARDANADAM" },

    { q: "<i class='fa-solid fa-arrow-right' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> 🦙", a: "SAĞLAMA" },


    { q: "<i class='fa-solid fa-person-skiing' style='color:#3498db'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-temperature-high' style='color:#e74c3c'></i>", a: "KAYISI" },

    { q: "<i class='fa-solid fa-arrow-down' style='color:#2c3e50'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-droplet' style='color:#3498db'></i> <span class='plus-sign'>+</span> <i class='fa-solid fa-wifi' style='color:#27ae60'></i>", a: "İNTERNET" }






];
